### ISSUE TITLE
where is the dataset

### ISSUE THREAD

**Issue by Facii** [kikumaru818/meta_math_scoring#1]

**Comment by kikumaru818** [comment]
Hi, The data cannot be publicly posted due to the potential existence of personally identifiable information contained within student open-response answers. In support of open science, this may be sharable through an IRB approval process. Inquiries should be directed to the trailing author of this work. Check this paper for details https://educationaldatamining.org/EDM2021/virtual/static/pdf/EDM21_paper_188.pdf.
